# Generated by Django 4.2.4 on 2023-08-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('lastName', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=200)),
                ('ort', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('birthDate', models.DateTimeField(max_length=200)),
                ('faberNumber', models.IntegerField()),
            ],
        ),
    ]
