# Generated by Django 4.2.4 on 2023-08-28 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField(max_length=200)),
                ('endDate', models.DateTimeField(max_length=200)),
                ('quota', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AlterField(
            model_name='person',
            name='faberNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrschule.coursecategory'),
        ),
    ]
