# Generated by Django 4.2.4 on 2023-08-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule', '0003_course_coursecategory_delete_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='faberNumber',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='person',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='person',
            name='street',
        ),
    ]
