# Generated by Django 4.2.4 on 2023-09-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule', '0005_person_birthdate_person_created_person_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlistedCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrschule.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahrschule.person')),
            ],
        ),
    ]
