# Generated by Django 4.2.4 on 2023-09-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrschule', '0006_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='courseCategory',
        ),
    ]
